BLOCK_SIZE = 4 * 1024
POINTER_SIZE = 4
DIRECT_POINTERS = 10
SINGLY_INDIRECT_POINTERS = 1
BYTEORDER = 'little'
POINTERS_PER_BLOCK = BLOCK_SIZE // POINTER_SIZE

TABLE_NAME_F = '200s'
COLUMN_COUNT_F = 'H'
COLUMN_NAME_F = '100s'
COLUMN_CODE_F = 'h'

TABLE_DDL_SIZE_F = 'H'
TABLE_IS_DELETED_F = '?'
